
APPLICATION=rtc
BOARD ?= native

RIOTBASE ?= $(CURDIR)/../../../RIOT

# Add shell related modules here

DEVELHELP ?= 1
USEMODULE += shell
USEMODULE += shell_commands
USEMODULE += ps
USEMODULE+=xtimer
FEATURES_REQUIRED += periph_rtc

include $(RIOTBASE)/Makefile.include


