APPLICATION=thread

BOARD ?= native

RIOTBASE ?= $(CURDIR)/../../../RIOT

# Add shell related modules here

DEVELHELP ?= 1
USEMODULE += shell
USEMODULE += shell_commands
USEMODULE += ps
USEMODULE+=xtimer

include $(RIOTBASE)/Makefile.include