APPLICATION = gpio_led_button
RIOTBASE ?= $(CURDIR)/../..
DEVELHELP ?= 1
USEMODULE += shell
USEMODULE += shell_commands
USEMODULE += ps
USEMODULE += xtimer
FEATURES_REQUIRED += periph_spi
FEATURES_OPTIONAL += periph_spi_reconfigure
FEATURES_REQUIRED += periph_gpio
FEATURES_OPTIONAL += periph_gpio_irq
# Change this to 0 show compiler invocation lines by default:
QUIET ?= 1


include $(RIOTBASE)/Makefile.include