APPLICATION = gpio_led_button
RIOTBASE ?= $(CURDIR)/../..
DEVELHELP ?= 1
USEMODULE += shell
USEMODULE += shell_commands
USEMODULE += ps
USEMODULE += xtimer
# Change this to 0 show compiler invocation lines by default:
QUIET ?= 1
FEATURES_REQUIRED = periph_gpio
FEATURES_OPTIONAL = periph_gpio_irq
include $(RIOTBASE)/Makefile.include